# Generated by Django 4.0.3 on 2022-04-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='bougth',
            field=models.BooleanField(default=False),
        ),
    ]
