# Generated by Django 4.0.3 on 2022-04-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingList', '0002_shoppinglist_bougth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
