# Generated by Django 4.0.4 on 2022-04-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingList', '0003_alter_shoppinglist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='bougth',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('bougth', models.BooleanField(default=False)),
                ('shoppinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingList.shoppinglist')),
            ],
        ),
    ]
